manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: EricDracula
      url-base: https://github.com/EricDracula
  projects:
    - name: zmk
      remote: EricDracula
      revision: dracula-test
      import: app/west.yml
  self:
    path: zmk-config
